import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import packagesRouter from "./packages";
import ordersRouter from "./orders";
import adminRouter from "./admin";
import reviewsRouter from "./reviews";
import partnerRouter from "./partner";
import openaiRouter from "./openai";
import storageRouter from "./storage";
import manualsRouter from "./manuals";
import videosRouter from "./videos";
import externalVideosRouter from "./external-videos";
import standardManualsRouter from "./standard-manuals";
import boardRouter from "./board";
import projectsRouter from "./projects";
import contractsRouter from "./contracts";
import notificationsRouter from "./notifications";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(packagesRouter);
router.use(ordersRouter);
router.use(adminRouter);
router.use(reviewsRouter);
router.use(partnerRouter);
router.use(openaiRouter);
router.use(storageRouter);
router.use(manualsRouter);
router.use(videosRouter);
router.use(externalVideosRouter);
router.use(standardManualsRouter);
router.use(boardRouter);
router.use(projectsRouter);
router.use(contractsRouter);
router.use(notificationsRouter);

export default router;
